# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectedUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#python NearbyWifi.py

import os
import subprocess

SEARCHip = b"Wi-Fi:"

def copynetip(netintip):
    li_ip=[]
    for i in range(len(netintip)):
        if SEARCHip in netintip[i]:
            break
    start_index=i+1
    for i in range(i+2,len(netintip)):
        li_ip.append(netintip[i].decode('UTF-8'))
    return(li_ip)

def get_ip():
    st=li_ip[1]
    a=st.split(":")
    print(st)
    print(a)
    ans=a[-1]
    return(ans.strip())

COMMANDip = "ipconfig"
netintip = subprocess.check_output(COMMANDip).split(b"\n")
li_ip=copynetip(netintip)

TERM_LINE = "Name"


def copynet(netint):
    li=[]
    for i in range(0,len(netint)-1):
        li.append(netint[i].decode('UTF-8'))
    #print(li)
    return(li)

def get_item1(i):
    st=li[i]
    a=st.split()
    ans=a[0].strip()
    return(ans)

def get_item2(i):
    st=li[i]
    a=st.split()
    ans=a[1].strip()
    return(ans)

def get_item3(i):
    st=li[i]
    a=st.split()
    ans=a[2].strip()
    return(ans)

COMMAND = "arp -a"
netint = subprocess.check_output(COMMAND).split(b"\n")
li=copynet(netint)
ipv4=get_ip()
SEARCH="Interface: "+ipv4+" --- 0x12\r"

i=0
for o in range(len(li)):
    if str(ipv4) in li[o]:
        i=o+1
        #print(o)
i=i+1

def copymac(macadd):
    maclis=[]
    for i in range(0,len(macadd)):
        maclis.append(macadd[i].decode('UTF-8'))
    return(maclis)

def get_mac(macli):
    st=macli[4]
    a=st.split()
    ans=a[0].strip()
    return(ans)

macadd = subprocess.check_output("getmac").split(b"\n")
macli=copymac(macadd)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 951, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"Background-color:white\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 951, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)

        j=i
        k=0
        while get_item3(j)=="dynamic":
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(1, k+1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(2, k+1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(3, k+1, item)
            j=j+1
            k=k+1

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, k+1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, k+1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, k+1, item)
        

        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, 320, 961, 361))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/users.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "USERS MONITOR"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Physical Address"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Users"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User 1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User 2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "User 3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "User 4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "User 5"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "User 6"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "User 7"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "User 8"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "User 9"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "User 10"))

        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form"," "))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "IP Address"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "Physical Address"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "Type"))
        j=i
        k=0
        while get_item3(j)=="dynamic":
            self.tableWidget.setSortingEnabled(False)
            item = self.tableWidget.item(1,k+1)
            item.setText(_translate("Form",get_item1(j)))
            item = self.tableWidget.item(2,k+1)
            item.setText(_translate("Form", get_item2(j)))
            item = self.tableWidget.item(3,k+1)
            item.setText(_translate("Form", get_item3(j)))
            if k==0:
                item.setText(_translate("Form", "Your Router"))
            j=j+1
            k=k+1
        item = self.tableWidget.item(1,k+1)
        item.setText(_translate("Form",ipv4))
        item = self.tableWidget.item(2,k+1)
        item.setText(_translate("Form",get_mac(macli).lower()))
        item = self.tableWidget.item(3,k+1)
        item.setText(_translate("Form","This PC"))

  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
